export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const SAVE_INFORMATION = "SAVE_INFORMATION";
export const SAVE_REGISTER = "SAVE_REGISTER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const GET_ALL_REGISTERS = "GET_ALL_REGISTERS";
//USER ACTIONS
export const GET_LIST_USERS_BY_ROLE = "GET_LIST_USERS_BY_ROLE";
export const SAVE_USER_REGISTER = "SAVE_USER_REGISTER";
export const EDIT_USER_REGISTER = "EDIT_USER_REGISTER";
export const GET_USER = "GET_USER";
export const GET_ACTION_TO_DO = "GET_ACTION_TO_DO";
export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
//ROLE ACTIONS
export const GET_LIST_ROLES_BY_ROLE = "GET_LIST_ROLES_BY_ROLE";
export const SAVE_ROLE_REGISTER = "SAVE_ROLE_REGISTER";
export const EDIT_ROLE_REGISTER = "EDIT_ROLE_REGISTER";
export const SAVE_ROLE_LIST = "SAVE_ROLE_LIST";
export const DELETE_ROLE_BY_ID = "DELETE_ROLE_BY_ID";
//USER ROLES ACTIONS
export const GET_LIST_USER_ROLES_BY_ROLE = "GET_LIST_USER_ROLES_BY_ROLE";
export const SAVE_USER_ROLE_REGISTER = "SAVE_USER_ROLE_REGISTER";
export const EDIT_USER_ROLE_REGISTER = "EDIT_USER_ROLE_REGISTER";
export const SAVE_USER_ROLE_LIST = "SAVE_USER_ROLE_LIST";
